sudo: required
services:
    - docker

before_install:
  - docker build -t ashishdhawal/docker-reactapp -f Dockerfile.dev .

script:
  - docker run ashishdhawal/docker-reactapp npm run test -- --coverage
   

